import Head from "next/head";
import { useRouter } from "next/router";
import MyComponent from "@/utils/MyComponent";

export default function Home() {
  const router = useRouter();
  const { testParam } = router.query;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>Client Page</div>
        <p>
          testParam should be a string if only supplied once in the URL query
          params. Otherwise, it should be an array.
        </p>
        {testParam && Array.isArray(testParam) && (
          <div>
            (Client page) testParam is an array: [
            {testParam.map((item, index) => (!index ? item : `, ${item}`))}]
          </div>
        )}
        {testParam && !Array.isArray(testParam) && (
          <div>(Client Page) testParam is a string: {testParam}</div>
        )}
        {!testParam && (
          <div>
            testParam: not set (hint set it twice to see the bug when deploy in
            netlify)
          </div>
        )}
      </main>
      <MyComponent />
    </>
  );
}
