import Head from "next/head";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();
  // get testParam
  const { testParam } = router.query;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>Main Page</div>
        <p>
          testParam should be a string if only supplied once in the URL query
          params. Otherwise, it should be an array.
        </p>
        {testParam && Array.isArray(testParam) && (
          <div>
            testParam is an array: [
            {testParam.map((item, index) => (!index ? item : `, ${item}`))}]
          </div>
        )}
        {testParam && !Array.isArray(testParam) && (
          <div>testParam is a string: {testParam}</div>
        )}
        {!testParam && (
          <div>testParam: not set (hit set it twice to seet bug)</div>
        )}
      </main>
    </>
  );
}
